# Latest golang image on apline linux
FROM golang:1.23-alpine

# Work directory
WORKDIR /docker-go

# Installing make

RUN apk add --no-cache make

# Installing dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copying all the files
COPY . .

# Starting our application
CMD ["make", "run"]

# Exposing server port
EXPOSE 8080
