version: "3.7"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gobank
      DB_PORT: 5432
    # command: make run
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobank
    ports:
      - "5433:5432"
    networks:
      - default
networks:
  default:
    driver: bridge
